<!--
	XML

	Copyright 2018-2019 MicroEJ Corp. All rights reserved.
	MicroEJ Corp. PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
-->

<ivy-module version="2.0" xmlns:ea="http://www.easyant.org" xmlns:ej="https://developer.microej.com" ej:version="2.0.0">
	<info organisation="com.microej.libraries.esp32" module="esp32-testsuite-ota" status="integration" revision="1.0.1">
		<ea:build organisation="com.is2t.easyant.buildtypes" module="build-microej-javaimpl" revision="3.+" rip.printableName="ESP32 OTA testsuite" microej.lib.name="esp32-testsuite-ota"/>
		<ea:property name="skip.test" value="set"/>
		<ea:property name="addon-processor.src.test.java.path.ref.name" value="src.java.path"/>
		<ea:property name="addon-processor.srctestjava.dir" value="${basedir}/src/main/java"/>
	</info>

	<configurations defaultconfmapping="default->default;provided->provided">
		<conf name="default" visibility="public" description="Runtime dependencies to other artifacts"/>
		<conf name="provided" visibility="public" description="Compile-time dependencies to APIs provided by the platform"/>
		<conf name="documentation" visibility="public" description="Documentation related to the artifact (javadoc, PDF)"/>
		<conf name="source" visibility="public" description="Source code"/>
		<conf name="dist" visibility="public" description="Contains extra files like README.md, licenses"/>
		<conf name="test" visibility="private" description="Dependencies for test execution. It is not required for normal use of the application, and is only available for the test compilation and execution phases."/>
	</configurations>

	<publications>
	</publications>

	<dependencies>
		<dependency org="ej.api" name="edc" rev="1.2.3" conf="provided->*"/>
		<dependency org="ej.api" name="bon" rev="1.3.0" conf="provided->*"/>

		<dependency org="com.microej.api" name="esp_idf" rev="1.0.1"/>

		<dependency org="ej.library.eclasspath" name="collections" rev="1.2.0"/>

		<dependency org="ej.library.test" name="junit" rev="1.4.2"/>
	</dependencies>
</ivy-module>
