/*
 * C
 *
 * Copyright 2018-2023 MicroEJ Corp. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be found with this software.
 */

#define LLBLUETOOTH_IMPL_enable Java_ej_bluetooth_BluetoothNatives_enable
#define LLBLUETOOTH_IMPL_disable Java_ej_bluetooth_BluetoothNatives_disable
#define LLBLUETOOTH_IMPL_waitEvent Java_ej_bluetooth_BluetoothNatives_waitEvent
#define LLBLUETOOTH_IMPL_startScanning Java_ej_bluetooth_BluetoothNatives_startScanning
#define LLBLUETOOTH_IMPL_stopScanning Java_ej_bluetooth_BluetoothNatives_stopScanning
#define LLBLUETOOTH_IMPL_startAdvertising Java_ej_bluetooth_BluetoothNatives_startAdvertising
#define LLBLUETOOTH_IMPL_stopAdvertising Java_ej_bluetooth_BluetoothNatives_stopAdvertising
#define LLBLUETOOTH_IMPL_connect Java_ej_bluetooth_BluetoothNatives_connect
#define LLBLUETOOTH_IMPL_disconnect Java_ej_bluetooth_BluetoothNatives_disconnect
#define LLBLUETOOTH_IMPL_sendPairRequest Java_ej_bluetooth_BluetoothNatives_sendPairRequest
#define LLBLUETOOTH_IMPL_sendPairResponse Java_ej_bluetooth_BluetoothNatives_sendPairResponse
#define LLBLUETOOTH_IMPL_sendPasskeyResponse Java_ej_bluetooth_BluetoothNatives_sendPasskeyResponse
#define LLBLUETOOTH_IMPL_discoverServices Java_ej_bluetooth_BluetoothNatives_discoverServices
#define LLBLUETOOTH_IMPL_addService Java_ej_bluetooth_BluetoothNatives_addService
#define LLBLUETOOTH_IMPL_sendReadRequest Java_ej_bluetooth_BluetoothNatives_sendReadRequest
#define LLBLUETOOTH_IMPL_sendWriteRequest Java_ej_bluetooth_BluetoothNatives_sendWriteRequest
#define LLBLUETOOTH_IMPL_sendReadResponse Java_ej_bluetooth_BluetoothNatives_sendReadResponse
#define LLBLUETOOTH_IMPL_sendWriteResponse Java_ej_bluetooth_BluetoothNatives_sendWriteResponse
#define LLBLUETOOTH_IMPL_sendPrepareWriteResponse Java_ej_bluetooth_BluetoothNatives_sendPrepareWriteResponse
#define LLBLUETOOTH_IMPL_sendExecuteWriteResponse Java_ej_bluetooth_BluetoothNatives_sendExecuteWriteResponse
#define LLBLUETOOTH_IMPL_sendNotification Java_ej_bluetooth_BluetoothNatives_sendNotification
