<!--
	IVY

	Copyright 2018-2020 MicroEJ Corp. All rights reserved.
	MicroEJ Corp. PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
-->

<ivy-module version="2.0" xmlns:ea="http://www.easyant.org" xmlns:ej="https://developer.microej.com" ej:version="2.0.0">
	<info organisation="com.is2t.ESP32.referencePlatforms.espressif.ESP32WROVER-${platform.uid}" module="bluetooth-testsuite" status="integration" revision="1.0.1">
		<ea:build organisation="com.is2t.easyant.buildtypes" module="build-microej-testsuite" revision="2.+"/>
		<ea:property name="microej.testsuite.kind" value="bluetooth"/>
		<ea:property name="microej.testsuite.dropins.dir" value="${basedir}/${microej.testsuite.kind}"/>
		<ea:property name="test.run.includes.pattern" value="**/central/**/_AllTests*.class"/>
		<ea:property name="test.run.excludes.pattern" value="**/*$*.class"/>
		<ea:property name="microej.testsuite.lockPort" value="0"/>
		<ea:property name="microej.testsuite.timeout" value="900"/>
		<ea:property name="microej.testsuite.jvmArgs" value="-Xmx768m"/>
		<ea:property name="target.vm.name" value="MICROJVM"/>
		<ea:property name="harness.file" value="${basedir}/bluetooth/microej-testsuite-harness.xml"/>
	</info>

	<configurations defaultconfmapping="default->default;provided->provided">
		<conf name="default" visibility="public" description="Runtime dependencies to other artifacts"/>
		<conf name="provided" visibility="public" description="Compile-time dependencies to APIs provided by the platform"/>
		<conf name="build-test" visibility="private"/>
		<conf name="test" visibility="private" description="Dependencies for test execution. It is not required for normal use of the application, and is only available for the test compilation and execution phases."/>
	</configurations>

	<publications>
	</publications>

	<dependencies>
		<dependency org="com.microej.pack.bluetooth" name="bluetooth-testsuite" rev="2.0.0" conf="test->default;provided->provided"/>

		<dependency org="com.is2t.ESP32.referencePlatforms.espressif" name="ESP32WROVER-${platform.uid}" rev="${platform.version}" conf="test->platformDev" transitive="false"/>
	</dependencies>
</ivy-module>
