<?xml version="1.0" encoding="UTF-8"?>
<!--
	IVY

	Copyright 2020-2021 MicroEJ Corp. All rights reserved.
	Use of this source code is governed by a BSD-style license that can be found with this software.
-->
<ivy-module version="2.0" xmlns:ea="http://www.easyant.org" xmlns:m="http://ant.apache.org/ivy/maven" xmlns:ej="https://developer.microej.com" ej:version="2.0.0"> 

	<info organisation="com.microej.testsuite" module="ota-testsuite-report" status="integration" revision="1.0.0">
        <ea:build organisation="com.is2t.easyant.buildtypes" module="build-microej-testsuite" revision="[2.2.0-RC0,3.0.0-RC0["/>
        <ea:plugin org="com.is2t.easyant.plugins" module="ivy-update" revision="1.+" />
	</info>

    <configurations>
		<conf name="default" />
		<conf name="provided" />
		<conf name="build-test" visibility="private" />
		<conf name="test" visibility="private" description="this scope indicates that the dependency is not required for normal use of the application, and is only available for the test compilation and execution phases."/>
    </configurations>

    <publications>
    </publications>

    <dependencies>
		<!--
			The testsuite module dependency (i.e. module that contains tests).
			The last module version is automatically fetched by default.
			To freeze the module version, add the following attribute: ej:match="perfect"
		-->
		<dependency org="com.microej.libraries.esp32" name="esp32-testsuite-ota"  rev="1.0.1" conf="test->default;provided->provided">
			<artifact type="rip"/>
		</dependency>
		<dependency org="com.microej.architecture.ESP32" name="esp_idf-testsuite"  rev="1.0.0" conf="test->default;provided->provided">
			<artifact type="rip"/>
		</dependency>
		<dependency org="com.is2t.libraries" name="checkHelper" rev="1.3.0" conf="default->default;provided->provided;test->default"/>	
		<dependency org="com.is2t.testsuite" name="benchHelper-1.0.0" rev="1.0.0" conf="test->default;provided->provided">
			<artifact type="rip" />
		</dependency>

    </dependencies>
</ivy-module>
